"""Add refund fields to payments table

Revision ID: bac8a1ac71d9
Revises: c7666ddfee21
Create Date: 2026-05-27 23:35:03.123109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac8a1ac71d9'
down_revision = 'c7666ddfee21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('refund_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('refund_reference')
        batch_op.drop_column('refunded_amount')

    # ### end Alembic commands ###
